name: Sync Documentation and Deploy MkDocs

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pyyaml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Sync documentation
        run: |
          python sync_docs.py
      
      - name: Commit changes to docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/ mkdocs.yml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-sync documentation from README files"
          git push
      
      - name: Build MkDocs site
        run: mkdocs build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
